# Generated by Django 5.1 on 2026-09-04 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact message', 'verbose_name_plural': 'Contact messages'},
        ),
    ]
