# Generated by Django 5.1 on 2026-08-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_newslettersubscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipapplication',
            name='full_name',
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='constituency',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='hometown',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='other_names',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='polling_station',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='residential_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='surname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='title',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='voter_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
