# Generated by Django 5.1 on 2026-08-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuesPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('tier', models.CharField(choices=[('Bronze', 'Bronze'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Diamond', 'Diamond')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
